### ISSUE TITLE
Show filters when using a json recipe

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#141]
When passing a recipe as parameter, the UI is not showing the filters used by recipe.

(From David:)
- [ ] implement basic support first in HXLStandard/libhxl-python#114
- [ ] add export link to edit page
- [ ] implement controller
- [ ] add controller unit test
- [ ] deploy to test branch and beta Proxy

**Comment by davidmegginson** [comment]
This would involve a fairly-big structural rewrite of the Proxy. Right now, JSON recipes and form-based recipes are separate things—the JSON comes first, then any form-based filters come after (which was fairly simple to implement).

That said, I see real value in being able to convert back and forth—e.g. create a recipe using the forms and save it as JSON, or create a recipe in JSON and edit it via the forms, so I'll keep this issue on the "Later" track.

The first step would be modifying libhxl-python so that an existing filter chain could serialise itself as JSON.

**Comment by davidmegginson** [comment]
Rejecting for now, but can reopen if the dev team is interesting in adding this functionality. The new Recipe class in release 1.16 will make it easier to implement this, by centralising the recipe logic in a single module.
