### ISSUE TITLE
Date cleaning inconsistent

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#164]
If you apply date cleaning here it assumes half are in format mm/dd/yyyy when day is less then 13.  All dates are in dd/mm/yyyy format

https://proxy.hxlstandard.org/data/edit?strip-headers=on&force=on&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1Yw11F4pghDr7JWhhqTe6dM42w7gqx7W86CFSn0kzKnc

**Comment by SimonbJohnson** [comment]
Since corrected source to ISO3 dates, but hope the explanation is still clear.

**Comment by davidmegginson** [comment]
The cleaning algorithm looks at each row in isolation so that it can work in streaming mode. One option would be to convert it to a non-streaming (memory-intensive) filter like sort, where it could scan the whole dataset in advance to find the best fit; another option would be to allow you to specify a default language/date/numbet locale for the filter try before it starts guessing.

**Comment by davidmegginson** [comment]
In this case, Python's date parser probably trying a US C locale for each row by default (which uses mm/dd/yy), the falling back to an international locale (dd/mm/yy) only when the first fails.

**Comment by davidmegginson** [comment]
It would be a major structural change to libhxl-python, but the ability to peek at the first (eg) 100 lines in a streaming context might make a big difference.

**Comment by davidmegginson** [comment]
Replaced by HXLStandard/libhxl-python#181
