### ISSUE TITLE
link broken - Philippines - Haima House Damage PCODED - NDRRMC Sitrep 9 

### ISSUE THREAD

**Issue by david-jankoski** [HXLStandard/hxl-proxy#166]
The link for the interactive map for damage by municipality on this page 
https://data.humdata.org/dataset/3cb60971-0dc7-4743-a7ae-e65744b2dbba
seems to be broken. 

The broken link:
https://proxy.hxlstandard.org/data/map?default_country=PHL&pcode_tag=%23adm3%2Bcode&value_tag=%23affected%2Bhouses%2Btotal&url=https%3A%2F%2Fdata.hdx.rwlabs.org%2Fdataset%2F3cb60971-0dc7-4743-a7ae-e65744b2dbba%2Fresource%2F968202f1-856a-4906-ae87-c730e9b1dd27&pcode_tag=%23adm3%2Bcode&default_country=PHL&verify=on

The error : 
Details
In machine-speak:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

thanks for a great service and data source.

**Comment by davidmegginson** [comment]
Thank you very much for the report, David. That visualisation was pointing to the old URL for HDX, and its SSL certificates are no longer valid. I've updated it to use the new data.humdata.org URL:

https://proxy.hxlstandard.org/data/map?url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2F3cb60971-0dc7-4743-a7ae-e65744b2dbba%2Fresource%2F968202f1-856a-4906-ae87-c730e9b1dd27&verify=on&default_country=PHL&value_tag=%23affected%2Bhouses%2Btotal&pcode_tag=%23adm3%2Bcode

I've also updated the gallery item on the dataset page, so that others won't see the same error.

**Comment by david-jankoski** [comment]
thank you!
