### ISSUE TITLE
Suggested value is not keeping the french accents

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#203]
low priority:
I spotted that the suggested value is not keeping the original french accents
https://beta.proxy.hxlstandard.org/data/validate.json?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1_TFjKh_rcZmYFjgEDhDXoya16piFZHMpmZgLzrqlS5Y%2Fexport%3Fformat%3Dcsv%26gid%3D2125848767%26single%3Dtrue&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fmaster%2Fvalidation-schema.json

<img width="1156" alt="screen shot 2018-04-24 at 11 23 15" src="https://user-images.githubusercontent.com/3865844/39178497-26fc7d4e-47b2-11e8-958c-07995dfc428d.png">

**Comment by davidmegginson** [comment]
Fixed in libhxl-python

Confirmation link: https://beta.proxy.hxlstandard.org/data/validate.json?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1_TFjKh_rcZmYFjgEDhDXoya16piFZHMpmZgLzrqlS5Y%2Fexport%3Fformat%3Dcsv%26gid%3D2125848767%26single%3Dtrue&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fmaster%2Fvalidation-schema.json

**Comment by davidmegginson** [comment]
@danmihaila - please confirm and close this issue if all is well

**Comment by danmihaila** [comment]
fixed! excellent!
