### ISSUE TITLE
wildcards seem not working well for datatype check

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#206]
https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F18bUp-oZKtNatP6c7jZxbE52Z5BGwJTOrwa3MIWAlt_g%2Fedit%23gid%3D0&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fmaster%2Fvalidation-schema-gin.json&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F18bUp-oZKtNatP6c7jZxbE52Z5BGwJTOrwa3MIWAlt_g%2Fedit%23gid%3D0

For this file https://docs.google.com/spreadsheets/d/18bUp-oZKtNatP6c7jZxbE52Z5BGwJTOrwa3MIWAlt_g/edit#gid=0 the wildcard "*" looks to check all columns even if they are not hxlated.

**Comment by davidmegginson** [comment]
Fixed in HXLStandard/libhxl-python#136

Confirmation link: https://beta.proxy.hxlstandard.org/data/validate?url=https%3A//docs.google.com/spreadsheets/d/18bUp-oZKtNatP6c7jZxbE52Z5BGwJTOrwa3MIWAlt_g/edit%23gid%3D0&schema_url=https%3A//raw.githubusercontent.com/OCHA-DAP/tools-datacheck-validation/master/validation-schema-gin.json&details=E4DofT8s

**Comment by davidmegginson** [comment]
@danmihaila - please check and close if all is well
