### ISSUE TITLE
Datatype check should be overridden by tag rather than guessed.

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#208]
Dataset: https://docs.google.com/spreadsheets/d/151wlMy_0Nb4GVvI4JPNijLNzU-jfwjDSiXjzpRTe2l0/edit#gid=836021560

Validation: https://beta.proxy.hxlstandard.org/data/validate?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F151wlMy_0Nb4GVvI4JPNijLNzU-jfwjDSiXjzpRTe2l0%2Fedit%23gid%3D836021560&schema_url=https%3A%2F%2Fraw.githubusercontent.com%2FOCHA-DAP%2Ftools-datacheck-validation%2Fmaster%2Fvalidation-schema-sle.json&details=E4DofT8s

Column M has #date and only one date value present and the date gets the error rather than the other values

Other possible overrides are attributes +values and +num

**Comment by davidmegginson** [comment]
Thanks, @SimonbJohnson . I think we need to consider more how we want wildcards to work, and when we think they might be useful.  For example,

    {
        "#valid_tag": "#date",
        "#valid_datatype": "date"
    }

will give exactly the result you want. I'm guessing, though, that you'd like to have a general rule that applies _only_ when there's no a more-specific one, so that (for example)

    {
        "#valid_tag": "#*",
        "#valid_datatype+consistent": true
    }

would ignore any columns covered by a rule with #valid_datatype and a more-specific (non-wildcard) tag pattern. This is doable, but non-trivial. The other option would be to hard-code knowledge of datatypes for key HXL hashtags like #date, #affected, etc. That's probably a faster fix.

I'll wait for feedback before working on this one.

**Comment by danmihaila** [comment]
this might be easier if we build a basic validation schema like the one we built for pcodes and say that when we find #date* it will always be a date...

**Comment by davidmegginson** [comment]
Sounds good. I'd also specify that #affected, #inneed, #targeted, and #reached always need to be numbers, and that #adm1+name should always correlate with #adm1+code (and so on up to #adm5+name and #adm5+code).

**Comment by davidmegginson** [comment]
Is this not critical for the sprint? If so, I'll move it to after the 1.7 (30 April) release.

**Comment by danmihaila** [comment]
not critical for the sprint, thanks

**Comment by SimonbJohnson** [comment]
> I'd also specify that #affected, #inneed, #targeted, and #reached always need to be numbers
+1

**Comment by davidmegginson** [comment]
Replaced with HXLStandard/libhxl-python#180
