### ISSUE TITLE
Extra empty row throws error

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#211]
If there is an extra empty row in the data it throws error
https://docs.google.com/spreadsheets/d/1TktaeD0LoiHbv8se7iZ6sciUAUZgFkbEYEaaugx9f7Y/edit#gid=1396660453
hxl proxy:
https://beta.proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1TktaeD0LoiHbv8se7iZ6sciUAUZgFkbEYEaaugx9f7Y%2Fedit%23gid%3D1396660453

<img width="1280" alt="screen shot 2018-04-25 at 12 03 39" src="https://user-images.githubusercontent.com/3865844/39239378-f1e3b51c-4880-11e8-8703-9fa973a6b953.png">

**Comment by mcarans** [comment]
Same issue for me with this: https://beta.proxy.hxlstandard.org/data/edit?url=http%3A%2F%2Fpopstats.unhcr.org%2Fen%2Fasylum_seekers_monthly.hxl

**Comment by davidmegginson** [comment]
Will be fixed in HXLStandard/libhxl-python#141

**Comment by davidmegginson** [comment]
Fixed in HXLStandard/libhxl-python#141

Confirmation links:
* https://beta.proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1TktaeD0LoiHbv8se7iZ6sciUAUZgFkbEYEaaugx9f7Y%2Fedit%23gid%3D1396660453
* https://beta.proxy.hxlstandard.org/data/edit?url=http%3A%2F%2Fpopstats.unhcr.org%2Fen%2Fasylum_seekers_monthly.hxl

**Comment by davidmegginson** [comment]
@danmihaila please test and close if resolved
