### ISSUE TITLE
Weird result on aggregation type "max" when using the "count" filter

### ISSUE THREAD

**Issue by alexandru-m-g** [HXLStandard/hxl-proxy#244]
https://proxy.hxlstandard.org/data/edit?filter01=cut&cut-include-tags01=%23date%2Bstart-activity&filter02=count&count-type02-01=max&count-pattern02-01=%23date%2Bstart&count-header02-01=Count&count-column02-01=%23meta%2Bcount&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1jvH0NwVnmasa_W7FeCe82Ygs-rEdn3sYev7222IB908%2Fedit%23gid%3D0

The above link returns "2017-01-02 00:00:00" as the maximum for the _#date+start_ column. The most recent in that column is however "2017-12-01 00:00:00"

**Comment by davidmegginson** [comment]
libhxl doesn't really handle times yet, just dates. I'm not sure yet if that's the problem here, Created the following issue to address it in libhxl-python:

HXLStandard/libhxl-python#190

**Comment by alexandru-m-g** [comment]
I see, then it makes sense that it might get confused with the timestamp columns from the example spreadsheet. 

I'm just adding another example where there's no ambiguity, #date+start matches exactly 1 column: https://proxy.hxlstandard.org/data/edit?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1af5xdRVHJpGi9sOmrQpaBP2Cy8L1JfQsGc_jfRwntXs%2Fedit%23gid%3D0&filter01=cut&cut-include-tags01=%23date%2Bstart-activity&filter02=count&count-type02-01=max&count-pattern02-01=%23date%2Bstart&count-header02-01=Count&count-column02-01=%23meta%2Bcount

**Comment by davidmegginson** [comment]
Fixed in libhxl-python: see HXLStandard/libhxl-python#190

Fix deployed to beta Proxy.

Test link now shows proper maximum date: https://beta.proxy.hxlstandard.org/data/edit?filter01=cut&cut-include-tags01=%23date%2Bstart-activity&filter02=count&count-type02-01=max&count-pattern02-01=%23date%2Bstart&count-header02-01=Count&count-column02-01=%23meta%2Bcount&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1jvH0NwVnmasa_W7FeCe82Ygs-rEdn3sYev7222IB908%2Fedit%23gid%3D0
