### ISSUE TITLE
Send user-agent string for requests

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#245]
Based on HXLStandard/libhxl-python#193, send special U-A strings for requests, as requested by @alexandru-m-g.

Initially, planning on these strings:

hxl-proxy/test - testing that a resource is HXL
hxl-proxy/download - downloading a resource for processing

**Comment by davidmegginson** [comment]
The Proxy _should_ now be sending three different user-agent strings:

hxl-proxy/test - for HXL testing
hxl-proxy/download - for downloading datasets
hxl-proxy/validation - for validating datasets

I don't have an easy way to test this. @alexandru-m-g, @danmihaila, or @teodorescuserban  -- could you try opening a dataset using https://beta.proxy.hxlstandard.org and see if the new user-agent appears in the server logs of the site hosting the dataset?

**Comment by mgalex** [comment]
@davidmegginson 
I tested with a dataset that wasn't hxlated and i got user agent: "hxl-proxy/tagger"
Then tested with a hxlated resource and got user agent: "hxl-proxy/download"
This is great, thanks. Let me know if there's anything else you need me to test.

Quick question: in a future version, will the prefix of the UA ( the "hxl-proxy" part) be configurable ? So that Serban could set them when deploying a HXL Proxy instance that has a specific purpose (like the one we use on tools) ?

**Comment by alexandru-m-g** [comment]
@davidmegginson
I tested with a dataset that wasn't hxlated and i got user agent: "hxl-proxy/tagger"
Then tested with a hxlated resource and got user agent: "hxl-proxy/download"
This is great, thanks. Let me know if there's anything else you need me to test.

Quick question: in a future version, will the prefix of the UA ( the "hxl-proxy" part) be configurable ? So that Serban could set them when deploying a HXL Proxy instance that has a specific purpose (like the one we use on tools) ?

**Comment by davidmegginson** [comment]
Tested successfully (thanks, @alexandru-m-g). Work will continue in #246

**Comment by davidmegginson** [comment]
I've added it for next month, but since I'm away for two weeks, it might
end up slipping.

https://github.com/HXLStandard/hxl-proxy/issues/246


Cheers, David
