### ISSUE TITLE
Support remote JSON recipes (formerly Run a Python filter)

### ISSUE THREAD

**Issue by mcarans** [HXLStandard/hxl-proxy#251]
It would be great to be able to run a filter coded in Python drawn from a url eg. on GitHub. This library could be used to prevent security issues: https://github.com/zopefoundation/RestrictedPython/

**Comment by davidmegginson** [comment]
Right now, you can encode filters in JSON (which avoids most of the security and performance risks):

https://github.com/HXLStandard/hxl-proxy/wiki/JSON-recipes

It would be a relatively small effort to load that from a URL instead of a POST or GET parameter. It does introduce yet one more point of failure (remote server could be down), but that's to be expected in the distributed-data world.

**Comment by mcarans** [comment]
David on the Python filters, the idea is not to run existing pre-defined filters but to be able to write an arbitrary filter in Python and have the HXL Proxy execute it.

**Comment by davidmegginson** [comment]
Thanks for the clarification, Mike. I think something like that is a good idea (and would fill that gap that ScraperWiki left), but I don't think it would be a good fit for the Proxy. One of the core design principles of the Proxy is that it's decarative (like CSS, SQL, or XSLT) rather than procedural (like Python or JavaScript). That simplifies caching and other optimisations, and allows for fairly-predictable performance under load.

Are there other systems we could look for your requirement? Maybe an open source ETL platform (@cjhendrix evaluated some of those a few years ago).

**Comment by mcarans** [comment]
It was to cover the kind of gap that CJ came across today where the HXL Proxy does most of what he needs but not all leaving the only option to fall back to a scraper.
