### ISSUE TITLE
Getting an error when using a "sort" filter

### ISSUE THREAD

**Issue by alexandru-m-g** [HXLStandard/hxl-proxy#345]
For this data file: https://docs.google.com/spreadsheets/d/e/2PACX-1vTqVOxCSrhEiZ_CRME3Xqhu_DWZv74FvrvOr77rIXOlorClEi0huwVKxXXcVr2hn8pml82tlwmf59UX/pub?output=xlsx the following JSON recipe generates an error:
```json
[
  {
    "filter": "with_rows",
    "queries": [
      "#affected+infected+confirmed+new is not empty"
    ]
  },
  {
    "filter": "clean_data",
    "date": "#date",
    "date_format": "%Y-%m-%d"
  },
  {
    "filter": "sort",
    "tags": "#date",
    "reverse": false
  }
]
```

And the HXL Proxy responds with the following error:
```json
{
    "error": "IndexError",
    "message": "list index out of range",
    "status": 500
}
```

The weird part is that the error seems to come from the last filter in the recipe, the **sort**.  If I remove that one then I don't get the error. Also, if I use the HXL Proxy **UI** to recreate the same filters, I don't get the error.

I noticed this while looking why these QCs are not being rendered: https://data.humdata.org/dataset/haiti-covid-19-subnational-cases/resource/615848f2-4f81-46ef-9cb8-aa50b11147e9?view_id=aa8867c2-1f4a-4248-a379-c9a2521475f6

**Comment by davidmegginson** [comment]
No error when recreating that sequence using the Proxy interactively (also tested with JSON output). That suggests that the bug might be in the API call for the Proxy, rather than inside libhxl-python.

https://proxy.hxlstandard.org/data/edit?dest=data_edit&filter01=select&select-query01-01=%23affected%2Binfected%2Bconfirmed%2Bnew+is+not+empty&filter02=clean&clean-date-tags02=%23date&clean-date-format02=%25Y-%25m-%25d&filter03=sort&sort-tags03=%23date&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vTqVOxCSrhEiZ_CRME3Xqhu_DWZv74FvrvOr77rIXOlorClEi0huwVKxXXcVr2hn8pml82tlwmf59UX%2Fpub%3Foutput%3Dxlsx

**Comment by davidmegginson** [comment]
Able to reproduce with this URL: https://proxy.hxlstandard.org/data?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vTqVOxCSrhEiZ_CRME3Xqhu_DWZv74FvrvOr77rIXOlorClEi0huwVKxXXcVr2hn8pml82tlwmf59UX%2Fpub%3Foutput%3Dxlsx&recipe=%5B%0D%0A++%7B%0D%0A++++%22filter%22%3A+%22with_rows%22%2C%0D%0A++++%22queries%22%3A+%5B%0D%0A++++++%22%23affected%2Binfected%2Bconfirmed%2Bnew+is+not+empty%22%0D%0A++++%5D%0D%0A++%7D%2C%0D%0A++%7B%0D%0A++++%22filter%22%3A+%22clean_data%22%2C%0D%0A++++%22date%22%3A+%22%23date%22%2C%0D%0A++++%22date_format%22%3A+%22%25Y-%25m-%25d%22%0D%0A++%7D%2C%0D%0A++%7B%0D%0A++++%22filter%22%3A+%22sort%22%2C%0D%0A++++%22tags%22%3A+%22%23date%22%2C%0D%0A++++%22reverse%22%3A+false%0D%0A++%7D%0D%0A%5D

**Comment by davidmegginson** [comment]
There are two bugs in libhxl-python combining to trigger this problem:

HXLStandard/libhxl-python#273 
HXLStandard/libhxl-python#274

I will fix the problems there, then come back to this issue and test before closing.

**Comment by davidmegginson** [comment]
Both bugs fixed in libhxl-python, and deployed to the beta Proxy. The recipe now sorts with no error:

https://beta.proxy.hxlstandard.org/data?url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vTqVOxCSrhEiZ_CRME3Xqhu_DWZv74FvrvOr77rIXOlorClEi0huwVKxXXcVr2hn8pml82tlwmf59UX%2Fpub%3Foutput%3Dxlsx&recipe=[%0D%0A++{%0D%0A++++%22filter%22%3A+%22with_rows%22%2C%0D%0A++++%22queries%22%3A+[%0D%0A++++++%22%23affected%2Binfected%2Bconfirmed%2Bnew+is+not+empty%22%0D%0A++++]%0D%0A++}%2C%0D%0A++{%0D%0A++++%22filter%22%3A+%22clean_data%22%2C%0D%0A++++%22date%22%3A+%22%23date%22%2C%0D%0A++++%22date_format%22%3A+%22%25Y-%25m-%25d%22%0D%0A++}%2C%0D%0A++{%0D%0A++++%22filter%22%3A+%22sort%22%2C%0D%0A++++%22tags%22%3A+%22%23date%22%2C%0D%0A++++%22reverse%22%3A+false%0D%0A++}%0D%0A]
