### ISSUE TITLE
xlsx file is triggering error

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#360]
Trying to preview or to view the files from this dataset: https://data.humdata.org/dataset/covid-19-twitter-data-geographic-distribution

https://proxy.hxlstandard.org/api/data-preview.json?url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2F70c2c71b-1322-4d44-83fc-6135e450b098%2Fresource%2F06394e45-2833-490b-a15a-6562bfe0fe6e%2Fdownload%2Fcc_geo_place.xlsx&format=json
![Screenshot 2021-06-14 at 11 38 33](https://user-images.githubusercontent.com/3865844/121864065-28ebba80-cd05-11eb-9b40-2ac7565ec93a.png)

**Comment by davidmegginson** [comment]
It took a while to figure it out, but here's the problem: those spreadsheets use the old transitional OOXML XML namespace URI "http://purl.oclc.org/ooxml/spreadsheetml/main" rather than the final (strict) OOXML XML namespace URI "http://schemas.openxmlformats.org/spreadsheetml/2006/main". I'm guessing these files were created programmatically, perhaps using some old code, rather than saved from Excel (etc).

Unfortunately, the Python xlrd3 library does not support the old transitional URI, so the library's not seeing any sheets. Excel and OpenOffice do still recognise the old URI on load, but will save it to the new URI on save.

Options:

1. Reach out to whoever created these XLSX files and ask them to update to use the more-common namespace URL (the schemas.openxmlformats.org one).
2. Choose a different library for processing XLSX files in libhxl
3. Temporarily for xlrd3 to add support for the transitional (purl.oclc.org) namespace URI, send the maintainer a PR, and hope it gets integrated into the next version.

Any preferences, @danmihaila ?

**Comment by danmihaila** [comment]
@davidmegginson per our conversation, the maintainer of the data will change the data format. I think we should revisit these options in case we want to use hxl-proxy for more data preview/view in browser. We can close this issue or leave it open for reference for later use.

**Comment by davidmegginson** [comment]
Closing for now, after verifying that the Excel files still don't work.
