### ISSUE TITLE
using the count[sum] filter will use the first column found

### ISSUE THREAD

**Issue by danmihaila** [HXLStandard/hxl-proxy#372]
There is a file with #inneed tag on several column (e.g #ineed+idps+m, #inneed+idps+f,) and the last column is #ineed+idps . When trying to compute the sum for last column, it will always return the first #inneed+idps+{attr} encountered. 

https://proxy.hxlstandard.org/data/edit?dest=data_edit&filter01=count&count-type01-01=sum&count-pattern01-01=%23inneed%2Bidps&count-header01-01=Sum&count-column01-01=%23meta%2Bsum&url=https%3A%2F%2Fdev.data-humdata-org.ahconu.org%2Fdataset%2Fbb82d66e-c7e3-46e5-9b80-14035434aba6%2Fresource%2F2295924f-633a-43c3-849c-855d91188ecf%2Fdownload%2Ftest-dan.csv
Tried several files and format and uploaded here https://dev.data-humdata-org.ahconu.org/dataset/dan-test-for-amadu

**Comment by davidmegginson** [comment]
Yes, that's a known feature of the HXL Proxy. There are two workarounds:

1. Ensure that Quick Charts is using the "!" notation in the hashtag pattern for an exact match (so "#inneed+idps!" rather than "#inneed+idps"). See https://github.com/HXLStandard/hxl-proxy/wiki/Tag-patterns#absolute-tag-patterns
2. Change the dataset to add a distinct attribute like "+total" to the last column.

**Comment by davidmegginson** [comment]
Here is your example with the "!" added: https://proxy.hxlstandard.org/data/edit?dest=data_edit&filter01=count&count-type01-01=sum&count-pattern01-01=%23inneed%2Bidps%21&count-header01-01=Sum&count-column01-01=%23meta%2Bsum&url=https%3A%2F%2Fdev.data-humdata-org.ahconu.org%2Fdataset%2Fbb82d66e-c7e3-46e5-9b80-14035434aba6%2Fresource%2F2295924f-633a-43c3-849c-855d91188ecf%2Fdownload%2Ftest-dan.csv
