### ISSUE TITLE
[HDX-8372] Default timeout for requests originating from Proxy

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/hxl-proxy#397]
libhxl-python already supports a timeout option. Use that to limit the amount of time that the requests library will wait for incoming data.

**Comment by davidmegginson** [comment]
Added a MAX_REQUEST_TIMEOUT config property to limit the timeout for requesting external datasets, in seconds. If not specified, defaults to 30 seconds. Needs testing.

**Comment by davidmegginson** [comment]
Please test at https://hxl.innovation.humdata.org/

@teodorescuserban @danmihaila

**Comment by teodorescuserban** [comment]
@davidmegginson @danmihaila made it configurable https://github.com/HXLStandard/hxl-proxy/commit/4852531ada8b5a6feab15bb069c52099f8632e97

Will deploy the test image on dev and report back.

**Comment by teodorescuserban** [comment]
@davidmegginson @danmihaila this works as expected, nice!

I tested against one of my own web servers on which I imposed 15 seconds wait efore the response. Configuring the `REQUEST_TIMEOUT` env var to 10 seconds, I was able to get 

```
{
    "error": "ReadTimeout",
    "message": "HTTPSConnectionPool(host='dev.data-humdata-org.ahconu.org', port=443): Read timed out. (read timeout=10)",
    "status": 403
}
```

instead of the usual (yeah, I didn't bother actually putting up something useful in there 😄 ):

```
{
    "error": "HXLIOException",
    "message": "Received HTML markup.\nCheck that the resource (e.g. a Google Sheet) is publicly readable.",
    "status": 403
}
```

I think this is ready to merge to dev and be included in the new release!

**Comment by davidmegginson** [comment]
Excellent! Thank you for testing.
