### ISSUE TITLE
Apply mapping table after append with column missing leads to 500

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/hxl-proxy#59]

**Comment by davidmegginson** [comment]
Testing: will append the two datasets and use the mapping table in https://docs.google.com/spreadsheets/d/1xU_nw0DupKWzx7YvzKCq0xqhI_zQzUCKgq08zNHf7ow/edit#gid=0

**Comment by davidmegginson** [comment]
Confirmed with error "List index is out of range."

http://proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1xU_nw0DupKWzx7YvzKCq0xqhI_zQzUCKgq08zNHf7ow%2Fedit%23gid%3D0&format=html&filter01=append&append-exclude-columns01=on&append-dataset01-01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1xU_nw0DupKWzx7YvzKCq0xqhI_zQzUCKgq08zNHf7ow%2Fedit%23gid%3D2023669444&append-dataset01-02=&append-dataset01-03=&append-dataset01-04=&append-dataset01-05=&append-dataset01-06=&append-dataset01-07=&append-dataset01-08=&append-dataset01-09=&append-dataset01-10=&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1xU_nw0DupKWzx7YvzKCq0xqhI_zQzUCKgq08zNHf7ow%2Fedit%23gid%3D763322780&filter03=&filter04=&filter05=&filter06=&filter07=

**Comment by davidmegginson** [comment]
Addressing with https://github.com/HXLStandard/libhxl-python/issues/51

**Comment by davidmegginson** [comment]
Fixed in HXLStandard/libhxl-python#51 and deployed to beta.  Test now passes:

http://beta.proxy.hxlstandard.org/data/edit?filter_count=7&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1xU_nw0DupKWzx7YvzKCq0xqhI_zQzUCKgq08zNHf7ow%2Fedit%23gid%3D0&format=html&filter01=append&append-exclude-columns01=on&append-dataset01-01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1xU_nw0DupKWzx7YvzKCq0xqhI_zQzUCKgq08zNHf7ow%2Fedit%23gid%3D2023669444&append-dataset01-02=&append-dataset01-03=&append-dataset01-04=&append-dataset01-05=&append-dataset01-06=&append-dataset01-07=&append-dataset01-08=&append-dataset01-09=&append-dataset01-10=&filter02=replace-map&replace-map-url02=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1xU_nw0DupKWzx7YvzKCq0xqhI_zQzUCKgq08zNHf7ow%2Fedit%23gid%3D763322780&filter03=&filter04=&filter05=&filter06=&filter07=

**Comment by davidmegginson** [comment]
Deployed to prod.  Initial test now passes.  Closing issue.
